### ISSUE TITLE
Auto Updating Link

### ISSUE THREAD

**Issue by okmrsavageYT** [SheepTester/htmlifier#26] opened 2020-08-02 23:45 UTC
I'm a bit new to GitHub, but correct me if I'm mistaken, I'm pretty sure this is where the suggestions go. I would like to see a live link that automatically updates when there is an update to the scratch project itself. This would be useful if I wished for part of a program I am making to include such a project, given its capability to connect to web servers. Whether this link is customizable by the website itself, (such as on a website like [beepbox.co](https://beepbox.co/) or made randomly, (like on an automatically made TinyURL) is completely up to you, so do as you see fit. Thank you for your time.

**Comment by SheepTester** [comment] 2021-08-08 01:46
I'm not entirely sure what you mean

If you want a link with the options pre-filled, you can copy the link address from "Save options in link" so that you can just click "Htmlify"

If you want the HTMLifier to create an HTML file that stays up to date by fetching directly from Scratch, then I'll close this as a duplicate of #21 to keep things in one place

**Comment by okmrsavageYT** [comment] 2021-08-08 05:08
I mad this issue so long ago lol
It was when I first started github, and probably before I knew what reddit
was. Point is, I didn't know how to look for duplicates. If it was a
duplicate, then I truly apologize.
It is an interesting concept though. It is a duplicate then. I'm sorry.

**Comment by SheepTester** [comment] 2021-08-08 05:23
It's only been a year, but maybe that's just because I'm becoming old 👴

I don't mind that this is a duplicate; I just want to make sure this issue isn't asking for something different. I'm guessing this is a duplicate, so I'll close this issue, but don't worry about it!

**Closed by SheepTester** 2021-08-08 05:23 UTC
