### ISSUE TITLE
Problem When Exporting A Project Using E羊icques

### ISSUE THREAD

**Issue by Rhet0rical** [SheepTester/htmlifier#105] opened 2021-08-08 23:11 UTC
When exporting a project, i usually open another client to see if it works and this time i came up with this error.
(https://user-images.githubusercontent.com/88635776/128648410-23d83703-06c9-49f1-bcb6-9ec89dfeee46.PNG)

**Comment by SheepTester** [comment] 2021-08-08 23:18
Interesting, it looks like one of your sprites has a sound file that is neither a .wav nor .mp3. If you send your project file or just its package.json, then maybe I can help figure out what's wrong

**Comment by Rhet0rical** [comment] 2021-08-08 23:21
Im unable to send it as a .sb3, so your going to have to convert it back to a .sb3 since im sending it as a .zip
[mod.zip](https://github.com/SheepTester/htmlifier/files/6951608/mod.zip)

**Comment by Rhet0rical** [comment] 2021-08-08 23:31
I previously exported the project with the same sound files in the same places. It exported fine and I was able to build of it.

Although it seems that in the "sb2Errors" thing, it says that something isn't named, or maybe it means something else and I'm not getting it :|

**Comment by SheepTester** [comment] 2021-08-08 23:40
I think the `sb2Errors` part can be ignored; Scratch tries to load the project as an .sb3 then an .sb2 by trial and error

It seems that the sound `Select 2` of sprite `Map - Sandbox` is apparently a file of type `x`, which is quite strange.

![image](https://user-images.githubusercontent.com/22133785/128648938-bc2b7cd5-50d2-40c0-a61c-7b91750e2591.png)

I see that in your zip file, there's both a 47edbd197764bcea748a6fcec124bf2d.wav and a 47edbd197764bcea748a6fcec124bf2d.x, which seem to be identical, so I'm assuming it's a wav file.

Here's a zip file containing the fixed project.json since GitHub doesn't let me upload .sb3 files either; you can just rename the .zip to a .sb3

[x replaced with wav.zip](https://github.com/SheepTester/htmlifier/files/6951626/x.replaced.with.wav.zip)

I'm not really sure how this happened, though; let's hope it doesn't happen again

Closing as I think the issue is resolved

**Closed by SheepTester** 2021-08-08 23:40 UTC

**Comment by Rhet0rical** [comment] 2021-08-09 00:45
Hello Sean, The Problem IS Resolved For The Most Part, But I'm Wondering How You Managed To Fix It Because Adding A New Sound Every time Still Produces The Same .x File.

**Comment by Rhet0rical** [comment] 2021-08-09 00:48
@SheepTester
